version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: opspilot
      POSTGRES_PASSWORD: opspilot
      POSTGRES_DB: opspilot
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.14.3
    command: >
      mlflow server
      --backend-store-uri postgresql://opspilot:opspilot@postgres:5432/opspilot
      --default-artifact-root /mlruns
      --host 0.0.0.0 --port 5000
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - mlruns:/mlruns

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  # Optional: comment out if using LLM_PROVIDER=mock
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    env_file:
      - .env
    environment:
      # Override URLs for Docker internal networking
      DATABASE_URL: postgresql+psycopg://opspilot:opspilot@postgres:5432/opspilot
      MLFLOW_TRACKING_URI: http://mlflow:5000
      REDIS_URL: redis://redis:6379/0
      OLLAMA_HOST: http://ollama:11434
    depends_on:
      - postgres
      - mlflow
      - redis
      - ollama
    ports:
      - "8000:8000"

  ui:
    build:
      context: .
      dockerfile: docker/ui.Dockerfile
    env_file:
      - .env
    environment:
      API_BASE_URL: http://api:8000
    depends_on:
      - api
    ports:
      - "8501:8501"

  prometheus:
    image: prom/prometheus:v2.53.1
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  pg_data:
  mlruns:
  grafana:
  ollama:
